### ISSUE TITLE
Add todo for this project

### ISSUE THREAD

**Issue by AlexanderChen1989** [iotalabs/elm-root#1]
## A boilerplate Project which must offer
- [ ] Automated Testing
- [ ] Linting
- [ ] Minification
- [ ] Bundling
- [ ] Simple command to do the jobs above
- A guidance to add different components
  - [ ] How to organize common/global components
  - [ ] How to organize folders based on features
  - [ ] How to organize files for a feature
    - View
    - Update
    - Store
    - Rest
## Problems we should consider
- [ ] How to Do Test
  - [ ] Testing frameworks
  - [ ] Assertion libraries
  - [ ] Helper libraries
- [ ] How to do api mock
- [ ] How to do async Reads/Writes
- [ ] How to handle Async Status and Errors
- [ ] How to use third-party libraries
- [ ] How to do route
## UI Components we may need
- [ ] Navigate
- [ ] Alert
- [ ] Layout
- [ ] Form
  - [ ] Input
  - [ ] Select
  - [ ] Button
- [ ] Tree
- [ ] Panel
- [ ] ProgressBar
- [ ] Table
- [ ] Modal

**Comment by AlexanderChen1989** [comment]
@ygmpkk @linuxr 我计划做一个模板项目，作为我们以后用elm开发界面的基础

**Comment by AlexanderChen1989** [comment]
代码组织我打算参考
http://blog.jenkster.com/2016/04/how-i-structure-elm-apps.html
https://github.com/coryhouse/react-slingshot

**Comment by ygmpkk** [comment]
@AlexanderChen1989 界面的UI是否可以参考ANTD的？

**Comment by linuxr** [comment]
这个内容应该放在README，或者项目中建一个TODO文件，然后通过git来管理追加和修改的内容。

我感觉 issue 被滥用了。。。

**Comment by linuxr** [comment]
just do IT 少年！ : )   @AlexanderChen1989

**Comment by ygmpkk** [comment]
@linuxr 莫激动啊，直接动手吧。。。 👊

**Comment by ygmpkk** [comment]
@AlexanderChen1989 这也是一个问题，到底什么东西该进代码库，什么东西该在Issue。立个原则吧

**Comment by AlexanderChen1989** [comment]
@ygmpkk @linuxr 这个应该进TODO.md
这个issue的目的是制定TODO.md

**Comment by AlexanderChen1989** [comment]
放在issue里面是方便讨论
